export async function onRequestGet({ request }) {
  const origin = new URL(request.url).origin;
  const body = [
    'User-agent: Googlebot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Naverbot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Yeti',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Googlebot-Image',
    'Allow: /',
    '',
    'User-agent: AdsBot-Google',
    'Allow: /',
    '',
    // AI / LLM crawlers — 전면 허용 정책 (뉴스 사이트 기본값).
    // 사이트 콘텐츠가 AI 답변·요약에 인용될 수 있도록 explicit allow.
    // 훈련만 거부하거나 특정 봇만 차단하려면 해당 User-agent 블록에서
    // Disallow: / 로 교체하면 됩니다. 관리·검색·출력 경로는 다른 봇과
    // 동일하게 차단.
    'User-agent: GPTBot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: ChatGPT-User',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: OAI-SearchBot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: ClaudeBot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Claude-Web',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: anthropic-ai',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Perplexity-User',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Google-Extended',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: CCBot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Applebot-Extended',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Amazonbot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Bytespider',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Meta-ExternalAgent',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: *',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    `Sitemap: ${origin}/sitemap.xml`,
    `Sitemap: ${origin}/sitemap-news.xml`,
  ].join('\n');

  return new Response(body, {
    headers: {
      'Content-Type': 'text/plain; charset=UTF-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
