export async function onRequestGet({ request }) {
  const origin = new URL(request.url).origin;
  const body = [
    'User-agent: Googlebot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Naverbot',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Yeti',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    'User-agent: Googlebot-Image',
    'Allow: /',
    '',
    'User-agent: AdsBot-Google',
    'Allow: /',
    '',
    'User-agent: *',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /admin.html',
    'Disallow: /dreampath',
    'Disallow: /dreampath.html',
    'Disallow: /kms',
    'Disallow: /kms.html',
    'Disallow: /search',
    'Disallow: /search.html',
    'Disallow: /api/',
    'Disallow: /output/',
    '',
    `Sitemap: ${origin}/sitemap.xml`,
  ].join('\n');

  return new Response(body, {
    headers: {
      'Content-Type': 'text/plain; charset=UTF-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
