import assert from 'node:assert/strict';
import { escapeText, pageNumber, pageHref, renderPagination, loadPublicPage, applyPublicParts } from '../functions/_shared/public-page-ssr.js';
assert.equal(escapeText('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;');
assert.equal(pageNumber(new URL('https://bpmedia.net/korea?page=2')), 2);
for (const bad of ['0','-1','2x','<script>']) assert.equal(pageNumber(new URL('https://bpmedia.net/korea?page='+encodeURIComponent(bad))),1);
const url = new URL('https://bpmedia.net/korea?page=2&sort=popular&period=7d');
assert.equal(pageHref(url,1), '/korea?sort=popular&period=7d');
assert.match(renderPagination(url,2,10), /href="\/korea\?page=3&amp;sort=popular&amp;period=7d"/);
assert.match(renderPagination(url,2,10), /aria-current="page"/);
const queries=[];
const env={DB:{prepare(sql){queries.push(sql);return {async all(){return {results:[{id:1,term_ko:'<script>x</script>',description_ko:'A&B'}]};}};}}};
const glossary=await loadPublicPage(env, new URL('https://bpmedia.net/glossary'), 'glossary');
assert.match(glossary.parts.glossary,/&lt;script&gt;/);
assert.doesNotMatch(glossary.parts.glossary,/<script>/);
assert.equal(applyPublicParts('<!-- PUBLIC_SSR:glossary -->',glossary),glossary.parts.glossary);
await loadPublicPage(env,new URL('https://bpmedia.net/memorabilia'),'memorabilia');
assert.ok(queries.some(sql => sql.includes("status = 'public'")));
await loadPublicPage(env,new URL('https://bpmedia.net/calendar'),'calendar');
assert.ok(queries.some(sql => sql.includes('p.published = 1')));
console.log('PASS public SSR escaping, public-only data and crawlable pagination');
const { publicAuthor, isPlaceholderAuthor } = await import('../functions/_shared/post-author.js');
assert.equal(publicAuthor('불러오는 중…'),'BP미디어');
assert.equal(publicAuthor('Editor A'),'Editor.A');
assert.equal(publicAuthor('실제 이름'),'실제 이름');
assert.equal(isPlaceholderAuthor('loading...'),true);
const { postLastmod } = await import('../functions/_shared/seo-dates.js');
assert.equal(postLastmod({publish_at:'2026-10-04 09:00:00',updated_at:'2026-10-03 00:00:00'}),'2026-10-04T00:00:00.000Z');
assert.equal(postLastmod({publish_at:'2026-10-04 09:00:00',updated_at:'2026-10-04 01:00:00'}),'2026-10-04T01:00:00.000Z');
assert.equal(postLastmod({created_at:'invalid',updated_at:'invalid'}),'');
const { onRequest: middleware } = await import('../functions/_middleware.js');
const redirect = await middleware({request:new Request('https://www.bpmedia.net/korea?page=2'),next(){throw Error('must redirect before next')}});
assert.equal(redirect.status,301);
assert.equal(redirect.headers.get('location'),'https://bpmedia.net/korea?page=2');
const { readFile } = await import('node:fs/promises');
const helpHtml = await readFile(new URL('../public/help.html',import.meta.url),'utf8');
const assetVersion = (await readFile(new URL('../public/ASSET_VERSION',import.meta.url),'utf8')).trim();
assert.ok([...helpHtml.matchAll(/\?v=(\d+)/g)].every(match => match[1] === assetVersion),'new help page must use the current asset token');
assert.ok(helpHtml.includes((await readFile(new URL('../public/VERSION',import.meta.url),'utf8')).trim()));
assert.ok(helpHtml.includes((await readFile(new URL('../public/ADMIN_VERSION',import.meta.url),'utf8')).trim()));
const { publicBoardRequest } = await import('../functions/_shared/public-page-ssr.js');
const publicRequest = publicBoardRequest(new URL('https://bpmedia.net/korea?q=검증&scope=admin&published=0'), 'korea', new Request('https://bpmedia.net/korea', {headers:{'CF-Connecting-IP':'192.0.2.1',Cookie:'admin_token=fixture-only',Authorization:'Bearer fixture-only'}}));
assert.equal(publicRequest.headers.get('CF-Connecting-IP'),'192.0.2.1','SSR search must retain the visitor rate-limit identity');
assert.equal(publicRequest.headers.get('Cookie'),null);
assert.equal(publicRequest.headers.get('Authorization'),null);
assert.equal(new URL(publicRequest.url).searchParams.has('scope'),false);
assert.equal(new URL(publicRequest.url).searchParams.has('published'),false);
