const GLOBAL_CITY_NAME_KO_MAP = {
  amman: '암만',
  amsterdam: '암스테르담',
  ankara: '앙카라',
  athens: '아테네',
  auckland: '오클랜드',
  بغداد: '바그다드',
  baghdad: '바그다드',
  bangkok: '방콕',
  barcelona: '바르셀로나',
  beijing: '베이징',
  beirut: '베이루트',
  ബെങ്കളൂരു: '벵갈루루',
  bengaluru: '벵갈루루',
  berlin: '베를린',
  bogota: '보고타',
  bogotá: '보고타',
  brussels: '브뤼셀',
  budapest: '부다페스트',
  buenosaires: '부에노스아이레스',
  cairo: '카이로',
  canberra: '캔버라',
  caracas: '카라카스',
  casablanca: '카사블랑카',
  chicago: '시카고',
  copenhagen: '코펜하겐',
  dakar: '다카르',
  damascus: '다마스쿠스',
  delhi: '델리',
  doha: '도하',
  دبي: '두바이',
  dubai: '두바이',
  dublin: '더블린',
  frankfurt: '프랑크푸르트',
  geneva: '제네바',
  hanoi: '하노이',
  helsinki: '헬싱키',
  hongkong: '홍콩',
  houston: '휴스턴',
  इस्तांबुल: '이스탄불',
  इस्तानबुल: '이스탄불',
  istanbul: '이스탄불',
  jakarta: '자카르타',
  جدة: '제다',
  jeddah: '제다',
  jerusalem: '예루살렘',
  johannesburg: '요하네스버그',
  kualalumpur: '쿠알라룸푸르',
  الكويت: '쿠웨이트시티',
  kuwaitcity: '쿠웨이트시티',
  kyiv: '키이우',
  kiev: '키이우',
  lagos: '라고스',
  lima: '리마',
  lisbon: '리스본',
  london: '런던',
  losangeles: '로스앤젤레스',
  luxembourg: '룩셈부르크',
  macau: '마카오',
  madrid: '마드리드',
  manila: '마닐라',
  مكة: '메카',
  mecca: '메카',
  melbourne: '멜버른',
  mexico: '멕시코시티',
  mexicocity: '멕시코시티',
  milan: '밀라노',
  مونتيفيديو: '몬테비데오',
  montevideo: '몬테비데오',
  montreal: '몬트리올',
  moscow: '모스크바',
  mumbai: '뭄바이',
  munich: '뮌헨',
  nairobi: '나이로비',
  newdelhi: '뉴델리',
  newyork: '뉴욕',
  اوسلو: '오슬로',
  oslo: '오슬로',
  ottawa: '오타와',
  paris: '파리',
  perth: '퍼스',
  phnompenh: '프놈펜',
  prague: '프라하',
  quito: '키토',
  riyadh: '리야드',
  rome: '로마',
  sanfrancisco: '샌프란시스코',
  santiago: '산티아고',
  saopaulo: '상파울루',
  seoul: '서울',
  shanghai: '상하이',
  singapore: '싱가포르',
  sofia: '소피아',
  stockholm: '스톡홀름',
  sydney: '시드니',
  taipei: '타이베이',
  tashkent: '타슈켄트',
  tbilisi: '트빌리시',
  tehran: '테헤란',
  tokyo: '도쿄',
  toronto: '토론토',
  tunis: '튀니스',
  ulaanbaatar: '울란바토르',
  ulaanbaatar: '울란바토르',
  vancouver: '밴쿠버',
  vienna: '빈',
  warsaw: '바르샤바',
  washington: '워싱턴',
  wellington: '웰링턴',
  zurich: '취리히',
};

const COUNTRY_CITY_NAME_KO_MAP = {
  KR: {
    seoul: '서울',
    busan: '부산',
    daegu: '대구',
    incheon: '인천',
    gwangju: '광주',
    daejeon: '대전',
    ulsan: '울산',
    sejong: '세종',
    suwon: '수원',
    jeju: '제주',
    jeonju: '전주',
    changwon: '창원',
    cheongju: '청주',
    pohang: '포항',
    gyeongju: '경주',
    yongin: '용인',
    seongnam: '성남',
  },
  JP: {
    tokyo: '도쿄',
    osaka: '오사카',
    kyoto: '교토',
    sapporo: '삿포로',
    fukuoka: '후쿠오카',
    nagoya: '나고야',
    yokohama: '요코하마',
    kobe: '고베',
    hiroshima: '히로시마',
    sendai: '센다이',
  },
  CN: {
    beijing: '베이징',
    shanghai: '상하이',
    guangzhou: '광저우',
    shenzhen: '선전',
    nanjing: '난징',
    tianjin: '톈진',
    chengdu: '청두',
    wuhan: '우한',
    xian: '시안',
    hangzhou: '항저우',
  },
  US: {
    newyork: '뉴욕',
    losangeles: '로스앤젤레스',
    sanfrancisco: '샌프란시스코',
    washington: '워싱턴',
    chicago: '시카고',
    seattle: '시애틀',
    boston: '보스턴',
    atlanta: '애틀랜타',
    dallas: '댈러스',
    houston: '휴스턴',
  },
};

export function normalizeCityNameKey(value) {
  return String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\u0600-\u06ff\u0900-\u097f\u0d00-\u0d7f\u4e00-\u9fff\u3040-\u30ff\u3131-\u318e\uac00-\ud7a3]+/g, '');
}

export function resolveCityLabelKo(countryCode, cityName) {
  const rawName = String(cityName || '').trim();
  if (!rawName) return '';
  if (/^[\u3131-\u318e\uac00-\ud7a3\s()\-]+$/.test(rawName)) return rawName;
  const normalized = normalizeCityNameKey(rawName);
  const country = String(countryCode || '').trim().toUpperCase();
  if (country && COUNTRY_CITY_NAME_KO_MAP[country] && COUNTRY_CITY_NAME_KO_MAP[country][normalized]) {
    return COUNTRY_CITY_NAME_KO_MAP[country][normalized];
  }
  if (GLOBAL_CITY_NAME_KO_MAP[normalized]) return GLOBAL_CITY_NAME_KO_MAP[normalized];
  return rawName;
}
