-- Source: https://atascout.org/events
-- Source: https://theme.archives.go.kr/next/organ/viewDetailInfo.do?code=OG0002302
-- Source: https://www.scouts.org.uk/volunteers/learning-development-and-awards/awards-and-recognition/award-certificates/
-- Source: https://pramuka.or.id/gerakan-pramuka/
-- Source: https://berita.rtm.gov.my/nasional/senarai-berita-nasional/senarai-artikel/pengakap-malaysia-terus-relevan-bentuk-integriti-dan-perpaduan-generasi-muda/
-- Source: https://www.scout.org/where-we-work/scouting-worldwide
-- Source: https://wspu.info/about/02.html?sMenu=02
-- Source: https://campfire.wagggs.org/fr/organization/india
-- Source: https://www.scout.or.jp/member/zenkokutaikai2025
-- Official-source glossary corrections, reviewed 2026-10-08.
-- Optimistic guards preserve concurrent editorial changes; reruns are idempotent.
UPDATE glossary_terms SET term_en='Association of Top Achiever Scouts (ATAS)', updated_at=CURRENT_TIMESTAMP WHERE id=11 AND bucket IS '사' AND term_ko IS '세계최고급위진급자모임' AND term_en IS 'Association of Top/Achiever Scout (ATAS)' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-14 07:50:20' AND updated_at IS '2026-10-08 01:48:24' AND description_ko IS '각국 스카우트의 최고 급위 또는 이에 준하는 성취를 이룬 이들이 교류하고 스카우트 정신과 봉사를 이어가는 네트워크이다. 최고 급위의 명칭과 인정 기준은 국가마다 다르다.';
UPDATE glossary_terms SET description_ko='한국스카우트연맹에서 수여하는 최고급위 스카우트 명칭이다. 스카우트 대원이 활동, 훈련, 봉사, 리더십 등 다양한 과정에서 요구되는 기준을 충족하고 최종 심사를 통과했을 때 수여되는 최고 단계의 성취 체계로, 미국의 Eagle Scout, 일본의 Fuji Scout와 유사한 개념이다. 범스카우트는 스카우트 기능과 활동 성취뿐 아니라 공동체 봉사, 리더십, 스카우트 정신을 종합적으로 인정받은 스카우트에게 부여되는 명예로운 성취 단계로 여겨진다.

참고로 범스카우트 제1호는 김용우 박사이다. 김용우 박사는 정동 소년단에서 스카우트 활동을 시작하였으며, 이후 학자이자 교육자로 활동하며 한국 스카우트 운동 발전에 기여하였다. 그는 제6대 국방부 장관(1956년 5월 26일~1957년 7월 6일)을 역임했으며, 학계와 공공 분야에서 활동하며 청소년 교육과 사회 발전에 기여한 인물로 알려져 있다.', updated_at=CURRENT_TIMESTAMP WHERE id=12 AND bucket IS '바' AND term_ko IS '범스카우트' AND term_en IS 'Tiger Scout' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-14 07:51:22' AND updated_at IS '2026-03-16 08:08:39' AND description_ko IS '한국스카우트연맹에서 수여하는 최고급위 스카우트 명칭이다. 스카우트 대원이 활동, 훈련, 봉사, 리더십 등 다양한 과정에서 요구되는 기준을 충족하고 최종 심사를 통과했을 때 수여되는 최고 단계의 성취 체계로, 미국의 Eagle Scout, 일본의 Fuji Scout와 유사한 개념이다. 범스카우트는 스카우트 기능과 활동 성취뿐 아니라 공동체 봉사, 리더십, 스카우트 정신을 종합적으로 인정받은 스카우트에게 부여되는 명예로운 성취 단계로 여겨진다.

참고로 범스카우트 제1호는 김용우 박사이다. 김용우 박사는 정동 소년단에서 스카우트 활동을 시작하였으며, 이후 학자이자 교육자로 활동하며 한국 스카우트 운동 발전에 기여하였다. 그는 제13대 국방부 장관을 역임했으며, 학계와 공공 분야에서 활동하며 청소년 교육과 사회 발전에 기여한 인물로 알려져 있다.';
UPDATE glossary_terms SET description_ko='영국 스카우트 조직 The Scout Association의 최고 공로상으로, 스카우트운동에 특별한 공헌을 한 이들에게 수여된다. 1908년 『Scouting for Boys』에서 처음 소개되었고 1909년 첫 수여가 이루어졌다. 1922년부터 성인 전용 포상으로 운영되었다. 은색 늑대 모양의 메달이 특징이다.', updated_at=CURRENT_TIMESTAMP WHERE id=79 AND bucket IS '사' AND term_ko IS '실버 울프 어워드' AND term_en IS 'Silver Wolf Award' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-16 04:18:55' AND updated_at IS '2026-03-16 04:18:55' AND description_ko IS '영국 스카우트 연맹인 The Scout Association이 수여하는 최고 공로상으로, 스카우트 운동에 대해 탁월하고 장기적인 봉사를 한 지도자에게 수여된다. 1922년에 제정된 상으로, 영국 스카우트에서 가장 높은 수준의 성인 공로상이며 일반적으로 매우 제한된 인원에게만 수여된다. 메달은 녹색과 노란색 리본에 매달린 은색 늑대 모양으로 제작되며, 스카우트 운동에 대한 헌신과 리더십을 상징한다.';
UPDATE glossary_terms SET description_ko='인도네시아를 대표하는 스카우트 연맹의 정식 명칭이다. 세계스카우트연맹의 회원국 조직으로, 인도네시아 전역에서 청소년 교육 프로그램을 운영한다.
‘Gerakan’은 운동을, ‘Pramuka’는 ‘Praja Muda Karana’의 약어를 뜻한다. 인도네시아 연맹은 이를 ‘Orang Muda yang Suka Berkarya’로 풀이하며, 창작·활동을 좋아하는 젊은이들이라는 취지이다. 인도네시아에서는 스카우트 활동이 학교 교육과 밀접하게 연계되어 운영되는 특징이 있다. 소속 지역연맹: 아시아태평양지역연맹. 명칭·회원 구분 기준: BP미디어 세계연맹 회원국 현황(2026-10-08 확인).', updated_at=CURRENT_TIMESTAMP WHERE id=85 AND bucket IS '아' AND term_ko IS '인도네시아 스카우트연맹' AND term_en IS 'Gerakan Pramuka' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-16 07:12:36' AND updated_at IS '2026-10-08 01:50:39' AND description_ko IS '인도네시아를 대표하는 스카우트 연맹의 정식 명칭이다. 세계스카우트연맹의 회원국 조직으로, 인도네시아 전역에서 청소년 교육 프로그램을 운영한다.
‘Gerakan Pramuka’는 ‘Praja Muda Karana’의 약어에서 유래한 명칭으로 “사회를 위해 봉사할 준비가 된 젊은 세대”라는 의미를 담고 있다. 인도네시아에서는 스카우트 활동이 학교 교육과 밀접하게 연계되어 운영되는 특징이 있다. 소속 지역연맹: 아시아태평양지역연맹. 명칭·회원 구분 기준: BP미디어 세계연맹 회원국 현황(2026-10-08 확인).';
UPDATE glossary_terms SET description_ko='인도네시아에서 스카우트를 지칭할 때 사용하는 명칭이다. 인도네시아스카우트연맹의 정식 명칭은 Gerakan Pramuka이며, 일상적으로 스카우트 대원이나 활동을 지칭할 때 ‘Pramuka’라는 표현이 널리 사용된다.
‘Pramuka’는 ‘Praja Muda Karana’의 약어이다. 인도네시아 연맹의 풀이인 ‘Orang Muda yang Suka Berkarya’는 창작·활동을 좋아하는 젊은이들이라는 취지이다. 인도네시아 스카우트 조직은 세계스카우트연맹의 회원국 조직이다.', updated_at=CURRENT_TIMESTAMP WHERE id=86 AND bucket IS '아' AND term_ko IS '인도네시아의 스카우트' AND term_en IS 'Pramuka' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-16 07:16:08' AND updated_at IS '2026-03-16 07:17:06' AND description_ko IS '인도네시아에서 스카우트를 지칭할 때 사용하는 명칭이다. 인도네시아스카우트연맹의 정식 명칭은 Gerakan Pramuka이며, 일상적으로 스카우트 대원이나 활동을 지칭할 때 ‘Pramuka’라는 표현이 널리 사용된다.
‘Pramuka’는 인도네시아어 Praja Muda Karana의 약어로, “일을 수행할 준비가 된 젊은 세대(Young people ready to serve)”라는 의미를 담고 있다. 인도네시아 스카우트 조직은 세계스카우트연맹의 회원국 조직이다.';
UPDATE glossary_terms SET description_ko='말레이시아의 로버스카우트 단계로, 학교 교육 이후 청년들이 공동체 봉사, 사회 프로젝트, 청년 리더십 활동 등을 이어가는 과정이다. 2026년 1월 말레이시아 공영방송 RTM의 연맹 관계자 인터뷰에서는 18~26세로 소개한다. 연령 상한의 적용과 가입·진급 자격은 연맹의 현행 규정 및 해당 프로그램 안내를 확인해야 한다.', updated_at=CURRENT_TIMESTAMP WHERE id=91 AND bucket IS '마' AND term_ko IS '말레이시아 로버스카우트' AND term_en IS 'Pengakap Kelana' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-16 07:24:34' AND updated_at IS '2026-03-16 07:24:34' AND description_ko IS '약 18~24세 연령대 단계로, 한국의 스카우트 체계에서 로버스카우트(Rover Scout) 단계에 해당한다. 공동체 봉사, 사회 프로젝트, 청년 리더십 활동 등을 중심으로 운영된다.';
UPDATE glossary_terms SET description_ko='인도의 스카우트 연맹으로, 1950년 여러 스카우트 단체의 통합을 통해 설립되었다. 인도에는 다양한 스카우트 단체가 존재하지만, The Bharat Scouts and Guides는 세계스카우트연맹과 세계걸스카우트연맹에 가입한 인도의 대표 스카우트 연맹으로 인정되고 있다. 소속 지역연맹: 아시아태평양지역연맹. 명칭·회원 구분 기준: BP미디어 세계연맹 회원국 현황(2026-10-08 확인).', updated_at=CURRENT_TIMESTAMP WHERE id=101 AND bucket IS '아' AND term_ko IS '인도 스카우트연맹' AND term_en IS 'The Bharat Scouts and Guides' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-16 07:36:13' AND updated_at IS '2026-10-08 01:50:39' AND description_ko IS '인도의 스카우트 연맹으로, 1950년 여러 스카우트 단체의 통합을 통해 설립되었다. 인도에는 다양한 스카우트 단체가 존재하지만, The Bharat Scouts and Guides는 세계스카우트연맹과 세계걸스카우트연맹에 가입한 인도의 대표 스카우트 연맹으로 인정되고 있다. 참고로 인도는 스카우트 역사에서 “단체가 가장 많이 분열되었다가 다시 통합된 국가 중 하나”이다. 소속 지역연맹: 아시아태평양지역연맹. 명칭·회원 구분 기준: BP미디어 세계연맹 회원국 현황(2026-10-08 확인).';
UPDATE glossary_terms SET term_ko='국가스카우트조직(NSO)', bucket='가', updated_at=CURRENT_TIMESTAMP WHERE id=122 AND bucket IS '하' AND term_ko IS '회원국' AND term_en IS 'National Scout Organisation (NSO)' AND term_fr IS 'Organisations Scoutes Nationales' AND sort_order IS 0 AND created_at IS '2026-03-17 00:40:03' AND updated_at IS '2026-10-08 01:50:39' AND description_ko IS '세계스카우트연맹의 회원 조직인 국가스카우트조직(NSO)을 뜻한다. 국가나 지역 자체가 아니라 그곳의 스카우트운동을 대표하여 WOSM 회원 자격을 가진 조직이다. 하나의 연맹이 NSO가 되기도 하고, 여러 국가스카우트협회(NSA)가 연합하여 하나의 NSO를 구성하기도 한다. 회원국 현황의 NSO·NSO Federation은 대표 조직이며, 소속 NSA 수와 WOSM 회원 조직 수를 혼동하지 않는다.';
UPDATE glossary_terms SET description_ko='스카우트운동을 지지하는 의원들을 연결하는 국제조직이다. 스카우트운동과 정책·입법 영역 간 협력을 강화하고, 청소년 교육을 위한 정책적 지원과 의회 간 교류를 촉진한다.', updated_at=CURRENT_TIMESTAMP WHERE id=129 AND bucket IS '사' AND term_ko IS '세계스카우트의원연맹' AND term_en IS 'World Scout Parliamentary Union (WSPU)' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-03-22 03:02:23' AND updated_at IS '2026-03-22 03:02:32' AND description_ko IS '스카우트 경험을 가진 국회의원들을 중심으로 구성된 국제 단체로, 스카우트운동과 정책·입법 영역 간 협력을 강화하는 것을 목적으로 한다. 정부 및 입법기관과의 연결, 정책 지원 기반 구축 등의 역할을 수행한다.';
UPDATE glossary_terms SET description_ko='일본스카우트연맹(Scout Association of Japan)이 매년 개최하는 전국 규모의 행사이다. 일본어 명칭은 「全国大会(ぜんこくたいかい, Zenkoku Taikai)」이다. 스카우트운동의 의의를 사회에 알리고 회원 간 교류와 정보교환을 촉진하는 것을 목적으로 한다.

개최지, 참가 규모와 세부 프로그램은 연도별 공고에 따른다. 2025년 안내에는 포상수여식, 전국스카우트교육회의, 스카우팅 엑스포(SCOUTING EXPO), 분야별 회의·설명회, 교환회(交歓会) 등이 포함되어 있다.', updated_at=CURRENT_TIMESTAMP WHERE id=135 AND bucket IS '자' AND term_ko IS '전국대회(全国大会)' AND term_en IS 'National Scout Convention' AND term_fr IS '' AND sort_order IS 0 AND created_at IS '2026-05-30 15:13:12' AND updated_at IS '2026-10-08 01:50:40' AND description_ko IS '일본스카우트연맹(Scout Association of Japan)이 매년 개최하는 전국 규모의 스카우트 행사이다. 스카우트 운동의 의의를 사회에 널리 알리고, 회원 간의 교류와 정보교환을 촉진하기 위해 개최된다. 일본어 명칭은 「全国大会(ぜんこくたいかい, Zenkoku Taikai)」이다.

전국대회는 매년 일본의 47개 도도부현이 순환 개최하며, 약 1,000명 이상의 지도자와 대원, 일반 참가자가 함께 참여한다. 행사 기간 동안 개회식, 포상수여식, 전국스카우트교육회의, 스카우팅 엑스포(SCOUTING EXPO), 분야별 회의 및 설명회, 교환회(交歓会) 등이 운영된다.

또한 스카우트 운동을 지역사회와 일반 대중에게 소개하는 사회적 홍보 기능을 수행하며, 일본연맹 회원으로서의 정체성과 소속감을 높이는 역할을 한다. 아울러 차기 개최지와 일본잼버리 등 주요 국가 행사를 홍보하고, 전국의 지도자와 대원들이 교류하며 정보를 공유하는 장으로 활용되고 있다.';
